### ISSUE TITLE
SEO対策

### ISSUE THREAD

**Issue by raahii** [piyo56/fashion-shop-map#2]
## 概要

検索流入を増やす必要がある。SEO対策を行い、

```(ファッション|セレクトショップ|服|ファッションブランド)　(店舗|地図|マップ|位置情報)```

などのワードで上位を狙う。

## TODO

[Ruby on Railsで開発したWebサービスでSEOをいろいろやってきた事をまとめた](http://qiita.com/na1412/items/cb4c2b5cb9825eae3719)

■ Search Console（旧ウェブマスターツール）の設定

- [x] サイト設定でwwwあり・なしを設定（※ SSL対応サイトの場合、https・httpも設定が必要）

- [x] URLのパラメータによる重複ページがある場合、パラメータを登録・設定

■ URL正規化

- ~~301リダイレクトでwwwあり・なし統一~~

- ~~301リダイレクトでindexあり・なし統一~~

- ~~SSL非対応サイトの場合、httpsでアクセスした場合httpに飛ばすなどの統一~~

■ URL・パンくずによるサイト構造

- [x] URL or パンくずによるサイト構造が低階層である（重要なページが2階層目にあるなど）

- [x] PCサイトで重要なコンテンツを非表示にしない（例：タブ切り替え、展開ボタンなどに重要コンテンツを含めない）

- [x] PCとスマホどちらからでも全ページにアクセスできる

- [x] パンくずリスト

■ meta title・description

- [x]  重要なキーワードを含むtitle・descriptionになっている

- [x]  内容が分かり、クリックしたくなるようなtitle・descriptionになっている

- ~~ページ固有のtitle・descriptionになっている（同じtitle・descriptionのページがあるのは良くない~~

■サイトマップxmlの作成・登録

- ~~サイトマップxmlの作成および最新の状態になっている~~

- ~~サイトマップxmlをSearch Consoleに登録している~~

■ その他

- [x] 全ページでh1が設定されている

- [x] 1ページ内に複数のh1がない

- [x] 重要なキーワードを含んだh1になっている

- [x] エラーページ作成（404エラーなど）

- ~~500エラーページ対応（適切なページや404へ301転送する）~~

- ~~ページネーションがあるページにページネーションタグを使用~~

- ~~PageSpeed Insightsの評価が良い~~

- [x] モバイルフレンドリーテストが合格
