### ISSUE TITLE
店舗の住所を正確なものに修正する

### ISSUE THREAD

**Issue by raahii** [piyo56/fashion-shop-map#5]
## 概要

開発段階ではジオコード（住所から経度, 緯度への変換）を行う関係で住所から建物名を除去する処理を行っていた。しかし、実際に地図を見る人にとっては例えば「ルミネ1階」などの情報はとても重要なのでもう一度スクレイピングし、復元する。

## TODO

- [ ] BEAMS

- [ ] UNITED ARROWS

- [ ] URBAN RESEARCH

- [ ] UNITED ARROWS green label relaxing

- [ ] URBAN RESEARCH DOORS

- [ ] FREAK'S STORE

- [ ] SHIPS

- [ ] EDIFICE

- [ ] 417 EDIFICE

- [ ] JOURNAL STANDARD

- [ ] coen

- [ ] BShop

- [ ] SENSE OF PLACE by URBAN RESEARCH

- [ ] HARE

- [ ] RAGEBLUE

- [ ] GLOBAL WORK

- [ ] UNITED ARROWS BEAUTY&YOUTH

- [x] UNIQLO

- [ ] A.P.C
